// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cRegis.Core.Data;

namespace cRegis.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200408155335_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "489d4fc0-3892-441b-b555-082ab933ca59",
                            ConcurrencyStamp = "82aab839-36bb-4638-9f64-28b031aaac2f",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "d7842d6b-1d12-440d-9dff-1a7c24897cb2",
                            ConcurrencyStamp = "d963210f-6440-46c1-a3de-25f710c7d02f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "faf7288f-42d3-4002-9790-c6eae272a016",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "6cc5ed4e-2e83-4bc0-a7d7-1eafa2f11b65",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "a88fa690-dd42-4336-a522-1ce9c83806b2",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "a9438dcb-76f0-4b39-ad5d-acd0aff6ca5b",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "fab73280-5f0d-433e-b133-5c81c8adb9a6",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "cb558c44-71d7-44f5-bc6b-8a031528d7d6",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        },
                        new
                        {
                            UserId = "2065db0a-d127-4f54-8566-7a6894228be1",
                            RoleId = "489d4fc0-3892-441b-b555-082ab933ca59"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("cRegis.Core.Entities.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("courseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("creditHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("space")
                        .HasColumnType("int");

                    b.HasKey("courseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            courseId = 1,
                            courseDescription = "An Introduction to Computer Science 1",
                            courseName = "COMP 1010",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 2,
                            courseDescription = "An Introduction to Computer Science 2",
                            courseName = "COMP 1020",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 3,
                            courseDescription = "Data Structure and Algorithm",
                            courseName = "COMP 2140",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 4,
                            courseDescription = "Program Practice",
                            courseName = "COMP 2160",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 5,
                            courseDescription = "Analysis of Algorithms",
                            courseName = "COMP 2080",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 6,
                            courseDescription = "Introduction to Computer Systems",
                            courseName = "COMP 2280",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 7,
                            courseDescription = "Object Orientation",
                            courseName = "COMP 2150",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 8,
                            courseDescription = "Graphics 1",
                            courseName = "COMP 3490",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 9,
                            courseDescription = "Software Engineer 1",
                            courseName = "COMP 3350",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 10,
                            courseDescription = "Analysis of Algorithms and Data Structures",
                            courseName = "COMP 3170",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 11,
                            courseDescription = "Operating Systems",
                            courseName = "COMP 3430",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 12,
                            courseDescription = "Computer Organization",
                            courseName = "COMP 3370",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 13,
                            courseDescription = "Artificial Intelligence 1",
                            courseName = "COMP 3190",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 14,
                            courseDescription = "Databases Concepts and Usage",
                            courseName = "COMP 3380",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 15,
                            courseDescription = "Computer Graphics",
                            courseName = "COMP 4490",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 16,
                            courseDescription = "Software Engineer 2",
                            courseName = "COMP 4350",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 17,
                            courseDescription = "Professional Practice in Computer Science",
                            courseName = "COMP 4620",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 18,
                            courseDescription = "Machine Learning",
                            courseName = "COMP 4360",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 19,
                            courseDescription = "Database Implementation",
                            courseName = "COMP 4380",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 20,
                            courseDescription = "Calculus 2",
                            courseName = "MATH 1700",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 21,
                            courseDescription = "Basic Statistical Analysis 1",
                            courseName = "STAT 1000",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 22,
                            courseDescription = "Introduction to Calculus",
                            courseName = "MATH 1500",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 23,
                            courseDescription = "Basic Statistical Analysis 2",
                            courseName = "STAT 2000",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 24,
                            courseDescription = "Introduction to Microeconomic Principles",
                            courseName = "ECON 1010",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 25,
                            courseDescription = "Introduction to Macroeconomic Principles",
                            courseName = "ECON 1020",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        },
                        new
                        {
                            courseId = 26,
                            courseDescription = "An Introduction to Modern World History: 1800 - Present(M)",
                            courseName = "HIST 1380",
                            creditHours = 3,
                            date = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            space = 5
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Enrolled", b =>
                {
                    b.Property<int>("enrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("completed")
                        .HasColumnType("bit");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("enrollId");

                    b.HasIndex("courseId");

                    b.HasIndex("studentId");

                    b.ToTable("Enrolled");

                    b.HasData(
                        new
                        {
                            enrollId = 1,
                            comment = "I like that course",
                            completed = true,
                            courseId = 1,
                            grade = 80,
                            rating = 90,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 2,
                            comment = "Very good",
                            completed = true,
                            courseId = 2,
                            grade = 90,
                            rating = 80,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 3,
                            comment = "Very interesting prof. Does a good job breaking down ideas into chunks you can easily understand",
                            completed = true,
                            courseId = 3,
                            grade = 95,
                            rating = 75,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 4,
                            comment = "I like the instructor",
                            completed = true,
                            courseId = 4,
                            grade = 95,
                            rating = 76,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 5,
                            comment = "Very good",
                            completed = true,
                            courseId = 5,
                            grade = 85,
                            rating = 82,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 6,
                            comment = "Franklin cannot take this one",
                            completed = true,
                            courseId = 6,
                            grade = 90,
                            rating = 87,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 7,
                            comment = "Excellent",
                            completed = true,
                            courseId = 7,
                            grade = 98,
                            rating = 93,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 8,
                            comment = "Good instructor",
                            completed = true,
                            courseId = 8,
                            grade = 97,
                            rating = 80,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 9,
                            completed = true,
                            courseId = 9,
                            grade = 96,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 10,
                            completed = true,
                            courseId = 11,
                            grade = 92,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 11,
                            completed = true,
                            courseId = 15,
                            grade = 87,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 12,
                            completed = true,
                            courseId = 14,
                            grade = 88,
                            studentId = 1
                        },
                        new
                        {
                            enrollId = 13,
                            comment = "NEVER AGAIN",
                            completed = true,
                            courseId = 1,
                            grade = 70,
                            rating = 70,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 14,
                            comment = "You will either love the course or hate time",
                            completed = true,
                            courseId = 2,
                            grade = 73,
                            rating = 80,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 15,
                            comment = "Awesome",
                            completed = true,
                            courseId = 3,
                            grade = 85,
                            rating = 90,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 16,
                            comment = "Very good professor, the best one I've had withery good professor, the best one I've had with",
                            completed = true,
                            courseId = 4,
                            grade = 75,
                            rating = 60,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 17,
                            comment = "The course thinks that everyone learns the same way (auditory). ",
                            completed = true,
                            courseId = 7,
                            grade = 70,
                            rating = 40,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 18,
                            comment = "Hard grader",
                            completed = true,
                            courseId = 8,
                            grade = 50,
                            rating = 20,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 19,
                            comment = "Nice Instructor",
                            completed = true,
                            courseId = 9,
                            grade = 68,
                            rating = 10,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 20,
                            completed = true,
                            courseId = 10,
                            grade = 65,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 21,
                            completed = true,
                            courseId = 13,
                            grade = 65,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 22,
                            completed = true,
                            courseId = 14,
                            grade = 50,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 23,
                            completed = false,
                            courseId = 6,
                            studentId = 2
                        },
                        new
                        {
                            enrollId = 24,
                            comment = "Very excellent professor. Very clear, informative, and very helpful. He knows his stuff very well! Can manage to balance his two positions in the Faculty of Science and Computer Science very well.",
                            completed = true,
                            courseId = 1,
                            grade = 90,
                            rating = 87,
                            studentId = 3
                        },
                        new
                        {
                            enrollId = 25,
                            comment = "Markers marks unnecessarily harsh. Like his intention is to fail you not to grade you. Nevertheless, he does do his best, and he is better than many.",
                            completed = true,
                            courseId = 2,
                            grade = 70,
                            rating = 90,
                            studentId = 3
                        },
                        new
                        {
                            enrollId = 26,
                            completed = true,
                            courseId = 3,
                            grade = 80,
                            studentId = 3
                        },
                        new
                        {
                            enrollId = 27,
                            completed = true,
                            courseId = 4,
                            grade = 70,
                            studentId = 3
                        },
                        new
                        {
                            enrollId = 28,
                            completed = false,
                            courseId = 6,
                            studentId = 3
                        },
                        new
                        {
                            enrollId = 29,
                            comment = "Excellent course",
                            completed = true,
                            courseId = 1,
                            grade = 90,
                            rating = 87,
                            studentId = 4
                        },
                        new
                        {
                            enrollId = 30,
                            comment = "Lectures were super easy to understand.",
                            completed = true,
                            courseId = 2,
                            grade = 80,
                            rating = 90,
                            studentId = 4
                        },
                        new
                        {
                            enrollId = 31,
                            completed = true,
                            courseId = 3,
                            grade = 90,
                            studentId = 4
                        },
                        new
                        {
                            enrollId = 32,
                            completed = true,
                            courseId = 4,
                            grade = 75,
                            studentId = 4
                        },
                        new
                        {
                            enrollId = 33,
                            completed = false,
                            courseId = 6,
                            studentId = 4
                        },
                        new
                        {
                            enrollId = 34,
                            comment = "Boring lectures. Easy mid term, harder final-assignments took a lot of time. ",
                            completed = true,
                            courseId = 1,
                            grade = 72,
                            rating = 58,
                            studentId = 5
                        },
                        new
                        {
                            enrollId = 35,
                            comment = "Don't bother going to the lectures.",
                            completed = true,
                            courseId = 2,
                            grade = 85,
                            rating = 68,
                            studentId = 5
                        },
                        new
                        {
                            enrollId = 36,
                            completed = true,
                            courseId = 3,
                            grade = 90,
                            studentId = 5
                        },
                        new
                        {
                            enrollId = 37,
                            completed = true,
                            courseId = 4,
                            grade = 75,
                            studentId = 5
                        },
                        new
                        {
                            enrollId = 38,
                            completed = false,
                            courseId = 6,
                            studentId = 5
                        },
                        new
                        {
                            enrollId = 39,
                            comment = "The course is knowledgeable and well prepared.",
                            completed = true,
                            courseId = 1,
                            grade = 98,
                            rating = 85,
                            studentId = 6
                        },
                        new
                        {
                            enrollId = 40,
                            comment = "I enjoyed this class, as I usually do.",
                            completed = true,
                            courseId = 2,
                            grade = 97,
                            rating = 98,
                            studentId = 6
                        },
                        new
                        {
                            enrollId = 41,
                            completed = true,
                            courseId = 3,
                            grade = 98,
                            studentId = 6
                        },
                        new
                        {
                            enrollId = 42,
                            completed = true,
                            courseId = 4,
                            grade = 88,
                            studentId = 6
                        },
                        new
                        {
                            enrollId = 43,
                            completed = false,
                            courseId = 6,
                            studentId = 6
                        },
                        new
                        {
                            enrollId = 44,
                            comment = "Notes aren't good for studying.",
                            completed = true,
                            courseId = 1,
                            grade = 75,
                            rating = 68,
                            studentId = 7
                        },
                        new
                        {
                            enrollId = 45,
                            comment = "Semi-entertaining lectures. Interesting fun guy to talk to but thinks a midterm average of apx. 60% is normal and fine.",
                            completed = true,
                            courseId = 2,
                            grade = 68,
                            rating = 67,
                            studentId = 7
                        },
                        new
                        {
                            enrollId = 46,
                            completed = true,
                            courseId = 3,
                            grade = 74,
                            studentId = 7
                        },
                        new
                        {
                            enrollId = 47,
                            completed = true,
                            courseId = 4,
                            grade = 72,
                            studentId = 7
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Faculty", b =>
                {
                    b.Property<int>("facultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("facultyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("graduateCreditHours")
                        .HasColumnType("int");

                    b.HasKey("facultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            facultyId = 1,
                            facultyName = "Computer Science",
                            graduateCreditHours = 60
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Prerequisite", b =>
                {
                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("prerequisiteId")
                        .HasColumnType("int");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.HasKey("courseId", "prerequisiteId");

                    b.HasIndex("prerequisiteId");

                    b.ToTable("Prerequisites");

                    b.HasData(
                        new
                        {
                            courseId = 2,
                            prerequisiteId = 1,
                            grade = 60
                        },
                        new
                        {
                            courseId = 3,
                            prerequisiteId = 2,
                            grade = 60
                        },
                        new
                        {
                            courseId = 4,
                            prerequisiteId = 2,
                            grade = 60
                        },
                        new
                        {
                            courseId = 5,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 6,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 6,
                            prerequisiteId = 4,
                            grade = 60
                        },
                        new
                        {
                            courseId = 7,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 8,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 9,
                            prerequisiteId = 7,
                            grade = 60
                        },
                        new
                        {
                            courseId = 10,
                            prerequisiteId = 3,
                            grade = 70
                        },
                        new
                        {
                            courseId = 11,
                            prerequisiteId = 6,
                            grade = 60
                        },
                        new
                        {
                            courseId = 11,
                            prerequisiteId = 4,
                            grade = 60
                        },
                        new
                        {
                            courseId = 12,
                            prerequisiteId = 6,
                            grade = 60
                        },
                        new
                        {
                            courseId = 13,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 14,
                            prerequisiteId = 3,
                            grade = 60
                        },
                        new
                        {
                            courseId = 15,
                            prerequisiteId = 8,
                            grade = 60
                        },
                        new
                        {
                            courseId = 16,
                            prerequisiteId = 9,
                            grade = 60
                        },
                        new
                        {
                            courseId = 17,
                            prerequisiteId = 9,
                            grade = 60
                        },
                        new
                        {
                            courseId = 18,
                            prerequisiteId = 10,
                            grade = 60
                        },
                        new
                        {
                            courseId = 18,
                            prerequisiteId = 13,
                            grade = 70
                        },
                        new
                        {
                            courseId = 19,
                            prerequisiteId = 11,
                            grade = 60
                        },
                        new
                        {
                            courseId = 19,
                            prerequisiteId = 14,
                            grade = 60
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Required", b =>
                {
                    b.Property<int>("facultyId")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.HasKey("facultyId", "courseId");

                    b.HasIndex("courseId");

                    b.ToTable("Required");

                    b.HasData(
                        new
                        {
                            facultyId = 1,
                            courseId = 1
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 2
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 3
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 4
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 5
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 6
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 7
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 11
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 12
                        },
                        new
                        {
                            facultyId = 1,
                            courseId = 17
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("majorId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.HasIndex("majorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            studentId = 1,
                            majorId = 1,
                            name = "John Braico"
                        },
                        new
                        {
                            studentId = 2,
                            majorId = 1,
                            name = "Mike Zapp"
                        },
                        new
                        {
                            studentId = 3,
                            majorId = 1,
                            name = "Peter Graham"
                        },
                        new
                        {
                            studentId = 4,
                            majorId = 1,
                            name = "Robert Guderian"
                        },
                        new
                        {
                            studentId = 5,
                            majorId = 1,
                            name = "Gord Boyer"
                        },
                        new
                        {
                            studentId = 6,
                            majorId = 1,
                            name = "Carson Leung"
                        },
                        new
                        {
                            studentId = 7,
                            majorId = 1,
                            name = "Franklin Bristow"
                        },
                        new
                        {
                            studentId = 8,
                            majorId = 1,
                            name = "Allan Marshall"
                        });
                });

            modelBuilder.Entity("cRegis.Core.Entities.Wishlist", b =>
                {
                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.HasKey("studentId", "courseId");

                    b.HasIndex("courseId");

                    b.ToTable("Wishlist");

                    b.HasData(
                        new
                        {
                            studentId = 1,
                            courseId = 13,
                            priority = 1
                        },
                        new
                        {
                            studentId = 1,
                            courseId = 16,
                            priority = 2
                        },
                        new
                        {
                            studentId = 1,
                            courseId = 17,
                            priority = 2
                        });
                });

            modelBuilder.Entity("cRegis.Core.Identities.StudentUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasIndex("StudentId");

                    b.HasDiscriminator().HasValue("StudentUser");

                    b.HasData(
                        new
                        {
                            Id = "faf7288f-42d3-4002-9790-c6eae272a016",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7994d5e2-fe56-49d9-bddd-df143913e905",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "JB",
                            PasswordHash = "AQAAAAEAACcQAAAAEDPWqJQsuo9unSHG6/BgRd6RVzo+JlXzrK4cXhx6Exm4E8kBYoGxGUYtmpvLF05SYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0b5a0f0b-ccdb-4804-ab0d-a2ac043fff6f",
                            TwoFactorEnabled = false,
                            UserName = "jb",
                            StudentId = 1
                        },
                        new
                        {
                            Id = "6cc5ed4e-2e83-4bc0-a7d7-1eafa2f11b65",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c76d47e-a5c4-48ea-ba0a-3e582af1781b",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEADV72/39bk+tK8FPtPZC8c/Nn7ypg5ShYEm5pA22kM4fGF8quz4NKvJ27wnQCyV2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "773586aa-7015-4e00-823e-356eedbac338",
                            TwoFactorEnabled = false,
                            UserName = "mz",
                            StudentId = 2
                        },
                        new
                        {
                            Id = "a88fa690-dd42-4336-a522-1ce9c83806b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc5033f3-ec4c-4f20-bfa9-1d15178fbac5",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "PG",
                            PasswordHash = "AQAAAAEAACcQAAAAEMPl4sMZH1LAb2sJZUZnT0fKWgpwNKU6piVZrN7dcSmv/c71ttwQWdS8fPGhVQD82Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61a8363d-7334-45d7-9c35-2038de2e736e",
                            TwoFactorEnabled = false,
                            UserName = "pg",
                            StudentId = 3
                        },
                        new
                        {
                            Id = "a9438dcb-76f0-4b39-ad5d-acd0aff6ca5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82838b53-0fcd-4421-931e-27eba89e5ccc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "RG",
                            PasswordHash = "AQAAAAEAACcQAAAAEKaawUKo9XZE3Mz23WWCd0hJvMQ+YDdkPLroGh3u7X5+ummzLVOAyHwxC6pGsQElaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75aad3b7-ac34-4380-973c-9b11df672ae1",
                            TwoFactorEnabled = false,
                            UserName = "rg",
                            StudentId = 4
                        },
                        new
                        {
                            Id = "fab73280-5f0d-433e-b133-5c81c8adb9a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87095d66-8ae7-4857-aaaa-33a3aa66e540",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "GB",
                            PasswordHash = "AQAAAAEAACcQAAAAEDBhXvr6SelSj5idsK/7t8glSixGvP6OEBXy+zJnbf0aXBqZ3DEF+BAuwkcQI5HDtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25973fb3-5b05-4d58-9c13-a6e112e0f7db",
                            TwoFactorEnabled = false,
                            UserName = "gb",
                            StudentId = 5
                        },
                        new
                        {
                            Id = "cb558c44-71d7-44f5-bc6b-8a031528d7d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "234c717d-2f51-4c7b-9df1-dae57b82d1a8",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "CL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFQfJKOfechObw36jPsJ/e+bWDe+B+7n4ZqprVoHnIt6iscdioTt75DDeZ84zkGa2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1073cbc5-b0f4-4bbf-a2fc-6d99367f3860",
                            TwoFactorEnabled = false,
                            UserName = "cl",
                            StudentId = 6
                        },
                        new
                        {
                            Id = "2065db0a-d127-4f54-8566-7a6894228be1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2ac8256-b36a-4bc8-9919-ab364a555e72",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "FB",
                            PasswordHash = "AQAAAAEAACcQAAAAEGjpNDb2NJ1vevomHkShUf63bakWFtQ+udytCrXXOKMwnelyxuu1CCmnhdLca9Go+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2643a991-e1a0-4c4e-9689-70f886f5f4b1",
                            TwoFactorEnabled = false,
                            UserName = "fb",
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Entities.Enrolled", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cRegis.Core.Entities.Student", "student")
                        .WithMany("enrolledCourses")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Entities.Prerequisite", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cRegis.Core.Entities.Course", "prerequisite")
                        .WithMany()
                        .HasForeignKey("prerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Entities.Required", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cRegis.Core.Entities.Faculty", "faculty")
                        .WithMany()
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Entities.Student", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Faculty", "major")
                        .WithMany()
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Entities.Wishlist", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Course", "course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cRegis.Core.Entities.Student", "student")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("cRegis.Core.Identities.StudentUser", b =>
                {
                    b.HasOne("cRegis.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
